//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace StationeersStructureXMLConverter {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class WorldData {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActiveMissions", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Atmospheres", typeof(WorldDataAtmospheres), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("BedrockLevel", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CableNetworks", typeof(WorldDataCableNetworks), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ChuteNetworks", typeof(WorldDataChuteNetworks), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Clouds", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CompletedMissions", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrentMission", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateTime", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DaysPast", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Game", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GameVersion", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ISpawnPoints", typeof(object), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Motherships", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("OriginPosition", typeof(PositionType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("OverallIndexOfContacts", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PipeNetworks", typeof(WorldDataPipeNetworks), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ResearchKey", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ResearchPodData", typeof(WorldDataResearchPodData), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RespawnDifficulty", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RocketShuttleNetworks", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Rooms", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SpawnPoints", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("StationContacts", typeof(WorldDataStationContacts), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SunTime", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Things", typeof(WorldDataThings), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("TileSystemData", typeof(WorldDataTileSystemData), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnlockedResearchHash", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UserInterface", typeof(WorldDataUserInterface), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("WeatherManagerData", typeof(WorldDataWeatherManagerData), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("WorldName", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("WorldSeed", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("WorldType", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorldDataAtmospheres {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AtmosphereSaveData", Order=0)]
        public AtmosphereSaveData[] AtmosphereSaveData;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AtmosphereSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CarbonDioxide", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Chlorine", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CleanBurnRate", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Direction", typeof(DirectionType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Energy", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Hydrogen", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LiquidCarbonDioxide", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LiquidHydrogen", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LiquidNitrogen", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LiquidNitrousOxide", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LiquidOxygen", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LiquidPollutant", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LiquidVolatiles", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MothershipReferenceId", typeof(System.Nullable<int>), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("NetworkReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Nitrogen", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("NitrousOxide", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Oxygen", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PollutedWater", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Position", typeof(PositionType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Steam", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ThingReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Volatiles", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Volume", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Water", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType20[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DirectionType : VectorType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Vector3Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EulerAnglesType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorldRotationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DirectionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PositionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorldPositionType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VectorType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float x;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float y;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float z;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FabricatorJobType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string JobType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Quantity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AtmosphereSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OreSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GrenadeSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JetpackSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlantSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DynamicGasCanisterSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BatterySaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PipeSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeviceAtmosphericSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransformerSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChuteSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeviceImportExportSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StackableSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SimpleFabricatorSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CableSaveSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MachineSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoorSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumableSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BatteryCellSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DynamicThingSaveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructureSaveData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomColorIndex", typeof(System.Nullable<int>), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CustomName", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DamageState", typeof(DamageStateType), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Indestructable", typeof(System.Nullable<bool>), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IsCustomName", typeof(System.Nullable<bool>), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("OwnerSteamId", typeof(System.Nullable<long>), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PrefabName", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Reagents", typeof(ReagentsType), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("States", typeof(ThingSaveDataBaseStates), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("WorldPosition", typeof(WorldPositionType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("WorldRotation", typeof(WorldRotationType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("eulerAngles", typeof(EulerAnglesType), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DamageStateType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float Brute;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BruteSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float Burn;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BurnSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float Oxygen;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OxygenSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float Hydration;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HydrationSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float Starvation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StarvationSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public float Toxic;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToxicSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public float Radiation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RadiationSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public float Stun;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StunSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReagentsType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reagent", Order=0)]
        public ReagentsTypeReagent[] Reagent;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ReagentsTypeReagent {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string TypeName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<float> Quantity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ThingSaveDataBaseStates {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("State", Order=0)]
        public ThingSaveDataBaseStatesState[] State;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ThingSaveDataBaseStatesState {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StateName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string State;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WorldPositionType : VectorType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WorldRotationType : VectorType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float w;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EulerAnglesType eulerAngles;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EulerAnglesType : VectorType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        CustomColorIndex,
        
        /// <remarks/>
        CustomName,
        
        /// <remarks/>
        DamageState,
        
        /// <remarks/>
        Indestructable,
        
        /// <remarks/>
        IsCustomName,
        
        /// <remarks/>
        OwnerSteamId,
        
        /// <remarks/>
        PrefabName,
        
        /// <remarks/>
        Reagents,
        
        /// <remarks/>
        ReferenceId,
        
        /// <remarks/>
        States,
        
        /// <remarks/>
        WorldPosition,
        
        /// <remarks/>
        WorldRotation,
        
        /// <remarks/>
        eulerAngles,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OreSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AngularVelocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DragOffset", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Dragged", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DraggedInteractionIndex", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HealthCurrent", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MothershipReferenceId", typeof(System.Nullable<int>), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentSlotId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Quantity", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("QuantitySmelted", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Velocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType19[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Vector3Type : VectorType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType19 {
        
        /// <remarks/>
        AngularVelocity,
        
        /// <remarks/>
        DragOffset,
        
        /// <remarks/>
        Dragged,
        
        /// <remarks/>
        DraggedInteractionIndex,
        
        /// <remarks/>
        HealthCurrent,
        
        /// <remarks/>
        MothershipReferenceId,
        
        /// <remarks/>
        ParentReferenceId,
        
        /// <remarks/>
        ParentSlotId,
        
        /// <remarks/>
        Quantity,
        
        /// <remarks/>
        QuantitySmelted,
        
        /// <remarks/>
        Velocity,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GrenadeSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AngularVelocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DragOffset", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Dragged", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DraggedInteractionIndex", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HealthCurrent", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Lifetime", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentSlotId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Velocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType18[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType18 {
        
        /// <remarks/>
        AngularVelocity,
        
        /// <remarks/>
        DragOffset,
        
        /// <remarks/>
        Dragged,
        
        /// <remarks/>
        DraggedInteractionIndex,
        
        /// <remarks/>
        HealthCurrent,
        
        /// <remarks/>
        Lifetime,
        
        /// <remarks/>
        ParentReferenceId,
        
        /// <remarks/>
        ParentSlotId,
        
        /// <remarks/>
        Velocity,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JetpackSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AngularVelocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DragOffset", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Dragged", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DraggedInteractionIndex", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HealthCurrent", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LeakRatio", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("OutputSetting", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentSlotId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Velocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType17[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType17 {
        
        /// <remarks/>
        AngularVelocity,
        
        /// <remarks/>
        DragOffset,
        
        /// <remarks/>
        Dragged,
        
        /// <remarks/>
        DraggedInteractionIndex,
        
        /// <remarks/>
        HealthCurrent,
        
        /// <remarks/>
        LeakRatio,
        
        /// <remarks/>
        OutputSetting,
        
        /// <remarks/>
        ParentReferenceId,
        
        /// <remarks/>
        ParentSlotId,
        
        /// <remarks/>
        Velocity,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlantSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AngularVelocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DragOffset", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Dragged", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DraggedInteractionIndex", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HarvestQuantity", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HealthCurrent", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MothershipReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentSlotId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Quantity", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Stage", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("StageTime", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Velocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType16[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType16 {
        
        /// <remarks/>
        AngularVelocity,
        
        /// <remarks/>
        DragOffset,
        
        /// <remarks/>
        Dragged,
        
        /// <remarks/>
        DraggedInteractionIndex,
        
        /// <remarks/>
        HarvestQuantity,
        
        /// <remarks/>
        HealthCurrent,
        
        /// <remarks/>
        MothershipReferenceId,
        
        /// <remarks/>
        ParentReferenceId,
        
        /// <remarks/>
        ParentSlotId,
        
        /// <remarks/>
        Quantity,
        
        /// <remarks/>
        Stage,
        
        /// <remarks/>
        StageTime,
        
        /// <remarks/>
        Velocity,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DynamicGasCanisterSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AngularVelocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DragOffset", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Dragged", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DraggedInteractionIndex", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HealthCurrent", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("OutputSetting", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentSlotId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Velocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType15[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType15 {
        
        /// <remarks/>
        AngularVelocity,
        
        /// <remarks/>
        DragOffset,
        
        /// <remarks/>
        Dragged,
        
        /// <remarks/>
        DraggedInteractionIndex,
        
        /// <remarks/>
        HealthCurrent,
        
        /// <remarks/>
        OutputSetting,
        
        /// <remarks/>
        ParentReferenceId,
        
        /// <remarks/>
        ParentSlotId,
        
        /// <remarks/>
        Velocity,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BatterySaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CurrentBuildState", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GoalPressure", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HasSpawnedWreckage", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MachineState", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MothershipReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PowerStored", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType14[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType14 {
        
        /// <remarks/>
        CurrentBuildState,
        
        /// <remarks/>
        GoalPressure,
        
        /// <remarks/>
        HasSpawnedWreckage,
        
        /// <remarks/>
        MachineState,
        
        /// <remarks/>
        MothershipReferenceId,
        
        /// <remarks/>
        PowerStored,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PipeSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CurrentBuildState", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HasSpawnedWreckage", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IsBurst", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MothershipReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PipeNetworkId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType13[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType13 {
        
        /// <remarks/>
        CurrentBuildState,
        
        /// <remarks/>
        HasSpawnedWreckage,
        
        /// <remarks/>
        IsBurst,
        
        /// <remarks/>
        MothershipReferenceId,
        
        /// <remarks/>
        PipeNetworkId,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeviceAtmosphericSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CurrentBuildState", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HasSpawnedWreckage", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MothershipReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("OutputSetting", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType12[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType12 {
        
        /// <remarks/>
        CurrentBuildState,
        
        /// <remarks/>
        HasSpawnedWreckage,
        
        /// <remarks/>
        MothershipReferenceId,
        
        /// <remarks/>
        OutputSetting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransformerSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CurrentBuildState", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GoalPressure", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HasSpawnedWreckage", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MachineState", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MothershipReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("OutputSetting", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType11[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType11 {
        
        /// <remarks/>
        CurrentBuildState,
        
        /// <remarks/>
        GoalPressure,
        
        /// <remarks/>
        HasSpawnedWreckage,
        
        /// <remarks/>
        MachineState,
        
        /// <remarks/>
        MothershipReferenceId,
        
        /// <remarks/>
        OutputSetting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChuteSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChuteNetworkId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrentBuildState", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HasSpawnedWreckage", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MothershipReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("NextNeighborId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType10[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType10 {
        
        /// <remarks/>
        ChuteNetworkId,
        
        /// <remarks/>
        CurrentBuildState,
        
        /// <remarks/>
        HasSpawnedWreckage,
        
        /// <remarks/>
        MothershipReferenceId,
        
        /// <remarks/>
        NextNeighborId,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeviceImportExportSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CurrentBuildState", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExportCount", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExportState", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HasSpawnedWreckage", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ImportCount", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ImportState", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MothershipReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType9[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType9 {
        
        /// <remarks/>
        CurrentBuildState,
        
        /// <remarks/>
        ExportCount,
        
        /// <remarks/>
        ExportState,
        
        /// <remarks/>
        HasSpawnedWreckage,
        
        /// <remarks/>
        ImportCount,
        
        /// <remarks/>
        ImportState,
        
        /// <remarks/>
        MothershipReferenceId,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StackableSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AngularVelocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DragOffset", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Dragged", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DraggedInteractionIndex", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HealthCurrent", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MothershipReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentSlotId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Quantity", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Velocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType8[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType8 {
        
        /// <remarks/>
        AngularVelocity,
        
        /// <remarks/>
        DragOffset,
        
        /// <remarks/>
        Dragged,
        
        /// <remarks/>
        DraggedInteractionIndex,
        
        /// <remarks/>
        HealthCurrent,
        
        /// <remarks/>
        MothershipReferenceId,
        
        /// <remarks/>
        ParentReferenceId,
        
        /// <remarks/>
        ParentSlotId,
        
        /// <remarks/>
        Quantity,
        
        /// <remarks/>
        Velocity,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SimpleFabricatorSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CurrentBuildState", typeof(System.Nullable<int>), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrentIndex", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExportCount", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExportState", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FabricatorJob", typeof(FabricatorJobType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HasSpawnedWreckage", typeof(System.Nullable<bool>), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ImportCount", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ImportState", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("JobQuantity", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MothershipReferenceId", typeof(System.Nullable<int>), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType7[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType7 {
        
        /// <remarks/>
        CurrentBuildState,
        
        /// <remarks/>
        CurrentIndex,
        
        /// <remarks/>
        ExportCount,
        
        /// <remarks/>
        ExportState,
        
        /// <remarks/>
        FabricatorJob,
        
        /// <remarks/>
        HasSpawnedWreckage,
        
        /// <remarks/>
        ImportCount,
        
        /// <remarks/>
        ImportState,
        
        /// <remarks/>
        JobQuantity,
        
        /// <remarks/>
        MothershipReferenceId,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CableSaveSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CableNetworkId", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrentBuildState", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HasSpawnedWreckage", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MothershipReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType6[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType6 {
        
        /// <remarks/>
        CableNetworkId,
        
        /// <remarks/>
        CurrentBuildState,
        
        /// <remarks/>
        HasSpawnedWreckage,
        
        /// <remarks/>
        MothershipReferenceId,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MachineSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CurrentBuildState", typeof(System.Nullable<int>), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FabricatorJob", typeof(FabricatorJobType), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GoalPressure", typeof(System.Nullable<float>), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HasSpawnedWreckage", typeof(System.Nullable<bool>), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MachineState", typeof(System.Nullable<int>), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MothershipReferenceId", typeof(System.Nullable<int>), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("OutputSetting", typeof(System.Nullable<int>), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PowerStored", typeof(System.Nullable<float>), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Setting", typeof(System.Nullable<int>), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType5[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType5 {
        
        /// <remarks/>
        CurrentBuildState,
        
        /// <remarks/>
        FabricatorJob,
        
        /// <remarks/>
        GoalPressure,
        
        /// <remarks/>
        HasSpawnedWreckage,
        
        /// <remarks/>
        MachineState,
        
        /// <remarks/>
        MothershipReferenceId,
        
        /// <remarks/>
        OutputSetting,
        
        /// <remarks/>
        PowerStored,
        
        /// <remarks/>
        Setting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoorSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CurrentBuildState", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HasSpawnedWreckage", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MothershipReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Setting", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType4[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType4 {
        
        /// <remarks/>
        CurrentBuildState,
        
        /// <remarks/>
        HasSpawnedWreckage,
        
        /// <remarks/>
        MothershipReferenceId,
        
        /// <remarks/>
        Setting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsumableSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AngularVelocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DragOffset", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Dragged", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DraggedInteractionIndex", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HealthCurrent", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentSlotId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Quantity", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Velocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType3[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType3 {
        
        /// <remarks/>
        AngularVelocity,
        
        /// <remarks/>
        DragOffset,
        
        /// <remarks/>
        Dragged,
        
        /// <remarks/>
        DraggedInteractionIndex,
        
        /// <remarks/>
        HealthCurrent,
        
        /// <remarks/>
        ParentReferenceId,
        
        /// <remarks/>
        ParentSlotId,
        
        /// <remarks/>
        Quantity,
        
        /// <remarks/>
        Velocity,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BatteryCellSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AngularVelocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DragOffset", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Dragged", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DraggedInteractionIndex", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HealthCurrent", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentSlotId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PowerStored", typeof(float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Velocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType2[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType2 {
        
        /// <remarks/>
        AngularVelocity,
        
        /// <remarks/>
        DragOffset,
        
        /// <remarks/>
        Dragged,
        
        /// <remarks/>
        DraggedInteractionIndex,
        
        /// <remarks/>
        HealthCurrent,
        
        /// <remarks/>
        ParentReferenceId,
        
        /// <remarks/>
        ParentSlotId,
        
        /// <remarks/>
        PowerStored,
        
        /// <remarks/>
        Velocity,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DynamicThingSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AngularVelocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DragOffset", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Dragged", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DraggedInteractionIndex", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HealthCurrent", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParentSlotId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Velocity", typeof(Vector3Type), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType1[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType1 {
        
        /// <remarks/>
        AngularVelocity,
        
        /// <remarks/>
        DragOffset,
        
        /// <remarks/>
        Dragged,
        
        /// <remarks/>
        DraggedInteractionIndex,
        
        /// <remarks/>
        HealthCurrent,
        
        /// <remarks/>
        ParentReferenceId,
        
        /// <remarks/>
        ParentSlotId,
        
        /// <remarks/>
        Velocity,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StructureSaveData : ThingSaveDataBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CurrentBuildState", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HasSpawnedWreckage", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MothershipReferenceId", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items1ElementName")]
        public object[] Items1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items1ElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items1ChoiceType[] Items1ElementName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType {
        
        /// <remarks/>
        CurrentBuildState,
        
        /// <remarks/>
        HasSpawnedWreckage,
        
        /// <remarks/>
        MothershipReferenceId,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PositionType : VectorType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum Items1ChoiceType20 {
        
        /// <remarks/>
        CarbonDioxide,
        
        /// <remarks/>
        Chlorine,
        
        /// <remarks/>
        CleanBurnRate,
        
        /// <remarks/>
        Direction,
        
        /// <remarks/>
        Energy,
        
        /// <remarks/>
        Hydrogen,
        
        /// <remarks/>
        LiquidCarbonDioxide,
        
        /// <remarks/>
        LiquidHydrogen,
        
        /// <remarks/>
        LiquidNitrogen,
        
        /// <remarks/>
        LiquidNitrousOxide,
        
        /// <remarks/>
        LiquidOxygen,
        
        /// <remarks/>
        LiquidPollutant,
        
        /// <remarks/>
        LiquidVolatiles,
        
        /// <remarks/>
        MothershipReferenceId,
        
        /// <remarks/>
        NetworkReferenceId,
        
        /// <remarks/>
        Nitrogen,
        
        /// <remarks/>
        NitrousOxide,
        
        /// <remarks/>
        Oxygen,
        
        /// <remarks/>
        PollutedWater,
        
        /// <remarks/>
        Position,
        
        /// <remarks/>
        Steam,
        
        /// <remarks/>
        ThingReferenceId,
        
        /// <remarks/>
        Volatiles,
        
        /// <remarks/>
        Volume,
        
        /// <remarks/>
        Water,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorldDataCableNetworks {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NetworkId", Order=0)]
        public int[] NetworkId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorldDataChuteNetworks {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NetworkId", Order=0)]
        public int[] NetworkId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorldDataPipeNetworks {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NetworkId", Order=0)]
        public int[] NetworkId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorldDataResearchPodData {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResearchPod", Order=0)]
        public WorldDataResearchPodDataResearchPod[] ResearchPod;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorldDataResearchPodDataResearchPod {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ResearchType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Quantity;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorldDataStationContacts {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StationContactData", Order=0)]
        public WorldDataStationContactsStationContactData[] StationContactData;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorldDataStationContactsStationContactData {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public WorldDataStationContactsStationContactDataAngle Angle;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ContactName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ContactType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float Lifetime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LifetimeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TradeItemData;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TraderInventorySelector;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int OverallIndex;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OverallIndexSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int VisitorCurrency;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VisitorCurrencySpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ContactID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContactIDSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorldDataStationContactsStationContactDataAngle {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float x;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float y;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float z;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorldDataThings {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ThingSaveData", Order=0)]
        public ThingSaveDataBase[] ThingSaveData;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorldDataTileSystemData {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Incidents;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VoxelFeatures;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EnteredTiles;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorldDataUserInterface {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OpenSlots;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SelectedButton;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ActiveHandSlot;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorldDataWeatherManagerData {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsWeatherEventRunning;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsWeatherEventRunningSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsWeatherEventScheduled;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsWeatherEventScheduledSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float WeatherStartTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeatherStartTimeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float WeatherEventLength;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeatherEventLengthSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int DaysSinceLastWeatherEvent;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DaysSinceLastWeatherEventSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int LastEventCoolDown;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastEventCoolDownSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        ActiveMissions,
        
        /// <remarks/>
        Atmospheres,
        
        /// <remarks/>
        BedrockLevel,
        
        /// <remarks/>
        CableNetworks,
        
        /// <remarks/>
        ChuteNetworks,
        
        /// <remarks/>
        Clouds,
        
        /// <remarks/>
        CompletedMissions,
        
        /// <remarks/>
        CurrentMission,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        DaysPast,
        
        /// <remarks/>
        Game,
        
        /// <remarks/>
        GameVersion,
        
        /// <remarks/>
        ISpawnPoints,
        
        /// <remarks/>
        Motherships,
        
        /// <remarks/>
        OriginPosition,
        
        /// <remarks/>
        OverallIndexOfContacts,
        
        /// <remarks/>
        PipeNetworks,
        
        /// <remarks/>
        ResearchKey,
        
        /// <remarks/>
        ResearchPodData,
        
        /// <remarks/>
        RespawnDifficulty,
        
        /// <remarks/>
        RocketShuttleNetworks,
        
        /// <remarks/>
        Rooms,
        
        /// <remarks/>
        SpawnPoints,
        
        /// <remarks/>
        StationContacts,
        
        /// <remarks/>
        SunTime,
        
        /// <remarks/>
        Things,
        
        /// <remarks/>
        TileSystemData,
        
        /// <remarks/>
        UnlockedResearchHash,
        
        /// <remarks/>
        UserInterface,
        
        /// <remarks/>
        WeatherManagerData,
        
        /// <remarks/>
        WorldName,
        
        /// <remarks/>
        WorldSeed,
        
        /// <remarks/>
        WorldType,
    }
}
